//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.Participants = new HashSet<Participants>();
        }
    
        public int EventId { get; set; }
        public Nullable<int> OrganizerId { get; set; }
        public string Image { get; set; }
        public string EventName { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> NumberOfTeams { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> AgeRestriction { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    
        public virtual GameTypes GameTypes { get; set; }
        public virtual ICollection<Participants> Participants { get; set; }
    }
}
