//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public int ParticipantId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EventId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
    }
}
